version: "3.8"
services:
# Build docker images
  spring-app:
    build: .
    container_name: j-spring-app
    restart: always
    ports:
      - "9100:9100"
    links:
      - mongodb:app_db
#  Install mongo
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456123

volumes:
  data: {}

networks:
  default:
    name: application-network


