spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      database: spring-mongo-db
      password: '123456123'
      port: '27018'
      host: 127.0.0.1
      auto-index-creation: true
  application:
    name: Spring Demo Validation In Deployment Environment
server:
  port: '9100'

application:
  baseName: messages
  defaultLocale: en


#spring.data.mongodb.port=27017
#spring.data.mongodb.host=localhost
#spring.data.mongodb.username=root
#spring.data.mongodb.password=123456123
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.database=spring-mongo-db
#spring.application.name=Spring Demo Validation
#server.port=9000
